### PR TITLE
NEXT-9116 - Fix long category names overflowing their boundaries

### PR DESCRIPTION
**Pull request by Agreon**
### 1. What does this change do, exactly?

This PR fixes the category names to overflow if they are too long. 

View without the change:

Screenshot from 2020-09-17 11-18-38

View with the change:

Screenshot from 2020-09-17 11-19-22

The cause for the behaviour was the use of the [experimental](https://developer.mozilla.org/de/docs/Web/CSS/width) value `max-content` for the width of tree-items. 

### 2. Describe each step to reproduce the issue or behaviour.

Give a category a too long name and the context menu trigger will disappear.

### 3. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/master/adr/2020-08-03-Implement-New-Changelog.md) with all necessary information about my changes
- [x] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by shyim** [comment]
It would be cool, when you could provide screenshots :)

**Comment by PaddyS** [comment]
Unfortunately you messed up the commits a bit. Hit me up if you need assistance with that.

**Comment by Agreon** [comment]
@PaddyS I actually don't know where they came from... If you got an easy fix in mind feel free to commit / tell me how to apply it.

**Comment by PaddyS** [comment]
Might want to try the following. Just please make sure that `origin` is actually pointing to the proper repository. Use `git remote -v` for that .

```
git checkout master
git pull origin master
git branch -D NEXT-9116-fix-long-category-names-no-elippsis
git cherry-pick 77b8eb7998835c7ea25981b71100003d97ef313b
git checkout -b next-9116-fix-long-category-names-no-elippsis
git push origin next-9116-fix-long-category-names-no-elippsis -f
```

**Pull request closed without merging**
